/** dados.js — 20 jogos mockados para o frontend SteamMatch */

const JOGOS = [
  {
    id: 1,
    nome: 'Counter-Strike 2',
    generos: ['FPS', 'Action', 'Multiplayer'],
    descricao: 'O FPS competitivo mais icônico do mundo. Escolha entre terroristas e contra-terroristas, plante ou defuse a bomba e use estratégia e mira precisa para vencer.',
    avaliacao: 87,
    total_avaliacoes: 7642084,
    fonte: 'Muito Positivo',
  },
  {
    id: 2,
    nome: 'Stardew Valley',
    generos: ['RPG', 'Simulation', 'Indie'],
    descricao: 'Herde a fazenda do avô e construa uma nova vida no campo. Cultive, crie animais, minere, pesque, faça amigos e talvez encontre o amor — tudo no seu ritmo.',
    avaliacao: 98,
    total_avaliacoes: 872384,
    fonte: 'Extremamente Positivo',
  },
  {
    id: 3,
    nome: 'Portal 2',
    generos: ['Puzzle', 'Adventure', 'Co-op'],
    descricao: 'Continue a saga de Chell nos labirintos da Aperture Science. Resolva puzzles com a portal gun e descubra os segredos sombrios da instalação — sozinho ou em co-op.',
    avaliacao: 98,
    total_avaliacoes: 349820,
    fonte: 'Extremamente Positivo',
  },
  {
    id: 4,
    nome: 'Hades',
    generos: ['Action', 'RPG', 'Indie', 'Roguelike'],
    descricao: 'Fuja do submundo grego em cada tentativa épica. Combine poderes dos deuses do Olimpo e desvende a história de sua família através de diálogos brilhantes.',
    avaliacao: 96,
    total_avaliacoes: 341209,
    fonte: 'Extremamente Positivo',
  },
  {
    id: 5,
    nome: 'Hollow Knight',
    generos: ['Action', 'Indie', 'Platformer'],
    descricao: 'Explore as profundezas de Hallownest, um reino de insetos em ruínas. Metroidvania desafiador com combate preciso e uma atmosfera melancólica inesquecível.',
    avaliacao: 97,
    total_avaliacoes: 522871,
    fonte: 'Extremamente Positivo',
  },
  {
    id: 6,
    nome: 'The Witcher 3: Wild Hunt',
    generos: ['RPG', 'Adventure', 'Action'],
    descricao: 'Encarne Geralt de Rívia em uma épica aventura de mundo aberto. Escolhas morais complexas, combate dinâmico e uma narrativa riquíssima num dos maiores mundos já criados.',
    avaliacao: 97,
    total_avaliacoes: 285463,
    fonte: 'Extremamente Positivo',
  },
  {
    id: 7,
    nome: 'Terraria',
    generos: ['Action', 'Adventure', 'Indie', 'Sandbox'],
    descricao: 'Cave, construa e lute em um mundo 2D infinito. Com centenas de inimigos, bosses épicos e itens raros, Terraria é a definição de progressão sandbox.',
    avaliacao: 98,
    total_avaliacoes: 1192345,
    fonte: 'Extremamente Positivo',
  },
  {
    id: 8,
    nome: 'Resident Evil 4 Remake',
    generos: ['Horror', 'Action', 'Adventure'],
    descricao: 'Leon Kennedy se infiltra em uma aldeia europeia infestada para resgatar a filha do presidente. Uma remasterização magistral que moderniza cada aspecto do original.',
    avaliacao: 93,
    total_avaliacoes: 138920,
    fonte: 'Extremamente Positivo',
  },
  {
    id: 9,
    nome: 'Cyberpunk 2077',
    generos: ['RPG', 'Action', 'Adventure'],
    descricao: 'V, mercenário em Night City, recebe um implante com a IA de uma lenda do rock. Explore uma metrópole cyberpunk com histórias ramificadas e escolhas que importam.',
    avaliacao: 87,
    total_avaliacoes: 683921,
    fonte: 'Muito Positivo',
  },
  {
    id: 10,
    nome: 'Celeste',
    generos: ['Indie', 'Platformer', 'Adventure'],
    descricao: 'Ajude Madeline a escalar a Montanha Celeste enquanto enfrenta seus medos internos. Plataforma preciso e desafiador com uma narrativa tocante sobre saúde mental.',
    avaliacao: 98,
    total_avaliacoes: 142983,
    fonte: 'Extremamente Positivo',
  },
  {
    id: 11,
    nome: 'Civilization VI',
    generos: ['Strategy', 'Simulation'],
    descricao: 'Construa um império que resistirá ao teste do tempo. Pesquise tecnologias, forme alianças, faça guerras e leve sua civilização da Pré-História até a Era Espacial.',
    avaliacao: 84,
    total_avaliacoes: 218374,
    fonte: 'Muito Positivo',
  },
  {
    id: 12,
    nome: 'Dota 2',
    generos: ['Strategy', 'MOBA', 'Multiplayer'],
    descricao: 'O MOBA mais profundo do mercado. Escolha entre mais de 100 heróis únicos e leve seu time à vitória destruindo o Ancient inimigo em partidas sempre diferentes.',
    avaliacao: 76,
    total_avaliacoes: 2037143,
    fonte: 'Muito Positivo',
  },
  {
    id: 13,
    nome: 'Dead Space Remake',
    generos: ['Horror', 'Action'],
    descricao: 'Isaac Clarke vai à USG Ishimura para resgatar sua namorada e encontra o inferno. Survival horror claustrofóbico com desmembramento estratégico e atmosfera aterrorizante.',
    avaliacao: 89,
    total_avaliacoes: 52834,
    fonte: 'Muito Positivo',
  },
  {
    id: 14,
    nome: 'Rocket League',
    generos: ['Sports', 'Action', 'Multiplayer'],
    descricao: 'Futebol com carros foguete. Suba a ranqueada dominando mecânicas de aerials, dribbles e boost management neste esporte competitivo único e extremamente viciante.',
    avaliacao: 87,
    total_avaliacoes: 910284,
    fonte: 'Muito Positivo',
  },
  {
    id: 15,
    nome: 'Disco Elysium',
    generos: ['RPG', 'Adventure', 'Indie'],
    descricao: 'Um detetive sem memória investiga um assassinato numa cidade decadente. RPG onde tudo é diálogo e escolhas, com um sistema de habilidades completamente único.',
    avaliacao: 97,
    total_avaliacoes: 87291,
    fonte: 'Extremamente Positivo',
  },
  {
    id: 16,
    nome: 'Among Us',
    generos: ['Strategy', 'Party', 'Multiplayer'],
    descricao: 'Complete tarefas na nave espacial enquanto um impostor tenta sabotar tudo. Engane ou seja enganado neste party game de dedução social irresistível.',
    avaliacao: 79,
    total_avaliacoes: 763821,
    fonte: 'Muito Positivo',
  },
  {
    id: 17,
    nome: 'Apex Legends',
    generos: ['FPS', 'Action', 'Battle Royale'],
    descricao: 'Battle Royale por equipes com lendas únicas e habilidades especiais. Movimentação fluida, comunicação por ping e tiro preciso num dos melhores battle royales.',
    avaliacao: 81,
    total_avaliacoes: 1284093,
    fonte: 'Muito Positivo',
  },
  {
    id: 18,
    nome: 'Divinity: Original Sin 2',
    generos: ['RPG', 'Strategy', 'Indie'],
    descricao: 'RPG por turnos premiado com liberdade criativa absurda. Jogue sozinho ou em co-op, mescle magias, manipule o ambiente e molde a história com suas escolhas.',
    avaliacao: 97,
    total_avaliacoes: 165920,
    fonte: 'Extremamente Positivo',
  },
  {
    id: 19,
    nome: 'Phasmophobia',
    generos: ['Horror', 'Multiplayer', 'Indie'],
    descricao: 'Seja um investigador paranormal com amigos e identifique o tipo de fantasma que assombra cada local. Use equipamentos reais e sobreviva às tentativas do espírito te eliminar.',
    avaliacao: 88,
    total_avaliacoes: 478320,
    fonte: 'Muito Positivo',
  },
  {
    id: 20,
    nome: 'FIFA 23',
    generos: ['Sports', 'Simulation', 'Multiplayer'],
    descricao: 'A simulação de futebol mais completa com times licenciados, Ultimate Team e carreira. Sinta a emoção do esporte mais popular do mundo em cada partida.',
    avaliacao: 55,
    total_avaliacoes: 183920,
    fonte: 'Misto',
  },
];
